# https://jekyllrb.com/tutorials/navigation/

- bar_title: "About"
  bar_menu:
  - title: "Configuration"
    url: "/content-docs/setup/configuration.html"
#  - title: "Change log"
#    url: "/content-docs/About/release-notes.html"

#- bar_title: "This site"
#  bar_menu:
#  - title: "About"
#  - title: "Change log"
#    url: "/content-docs/about/change-log.html"
