@startuml
'scale 0.9
skinparam packageStyle rectangle
'set namespaceSeparator ::
hide members

package QAManager {
  class QAManager
  class QAManager::Category
  class QAManager::Sheet
  class QAManager::Gui::TopLevel
  class QAManager::Gui::Main
  class QAManager::QATypes
  class QAManager::Set
  class QAManager::KV
  'class QAManager
  'class QAManager
}

QAManager --> QAManager::Category
QAManager --> QAManager::Sheet
QAManager --> QAManager::Gui::TopLevel

QAManager::Category --> QAManager::Set
QAManager::Category --> QAManager::KV

QAManager::Sheet --> QAManager::QATypes

QAManager::Gui::TopLevel --> QAManager::Gui::Main

QAManager::Gui::Main --> QAManager::QATypes
QAManager::Gui::Main --> QAManager::Set


@enduml
